### ISSUE TITLE
Add Dynamic Value Parsing

### ISSUE THREAD

**Issue by yusufcanb** [yusufcanb/enohub#1]
Allow user to choose which parsed EEP values should be inserted into InfluxDB like below ;

```yaml

# ...

devices: # Array of registered devices map. IDs can be found on the backside of every device.
  - id: 04211ABE
    name: sensor-1
    eep:	d2-14-41
    values:
      - "TMP"
      - "HUM"
      - "ILL"
      - "ACC"
      - "ACX"
      - "ACY"
      - "CO"

# ....

```
