### ISSUE TITLE
Allow individual sensor group assigment per device

### ISSUE THREAD

**Issue by yusufcanb** [yusufcanb/enohub#2]
Allow device config to have `sensor_group` property so it can individually added to a `sensor_group`. If not exists it should fallback to `name` as sensor group;

```yaml

name: kitchen # Display name of the sensor group. E.g living-room, kitchen, keller.
port: /dev/ttyUSB0 # Serial port which EnOcean USB 3000 connected.

devices: # Array of registered devices map. IDs can be found on the backside of every device.
  - id: 04211ABE
    name: sensor-1
    eep:	d2-14-41
    group: overrided-group

  # This below will have default as kitchen
  - id: 0420FCCD
    name: co2
    eep:	a5-09-09
```
